###GET http://localhost:8080/solution_sql/result/1

###

#GET http://localhost:8080/solutionSql/result/
#parameter "Select e from EMP"

### ??
POST http://localhost:8080/datamodel/add_datamodel
Content-Type: application/json

{

  "name": "Datamodel01",
  "person": {
    "firstName": "Lisa",
    "lastName": "Gruber",
    "role": "STUDENT"
  },
  "comment": "comment1"
}


###

GET http://localhost:8080/datamodel/getbyid/3

###


GET http://localhost:8080/datamodel/get_all
Accept: application/json


#### ??
POST http://localhost:8080/person/add_person
Content-Type: application/json

{
    "firstName": "Sabrina",
    "lastName": "Haus",
    "role": "ADMIN"
}

###

GET http://localhost:8080/person/getbyid/3


###

GET http://localhost:8080/person/get_all
Accept: application/json


### ??
POST http://localhost:8080/question/add_question
Content-Type: application/json

{
  "text": "text01",
  "sql": "Select p from Person p order by p.lastName",
  "points": 2,
  "datamodel": {
    "name": "Datamodel01",
    "person": {
      "firstName": "Lisa",
      "lastName": "Gruber",
      "role": "STUDENT"
    },
    "comment": "comment1"
  },
  "person": {
    "firstName": "madschi",
    "lastName": "stei",
    "role": "ADMIN"
  }
}

###

GET http://localhost:8080/question/getbyid/3

###

GET http://localhost:8080/question/get_all
Accept: application/json


###

POST http://localhost:8080/sqlscript/add_sqlscript
Content-Type: application/json

{
  "datamodel":{
    "name": "Datamodel03",
    "person": {
      "firstName": "Marah",
      "lastName": "Steigersdorfer",
      "role": "ADMIN"
    },
  "comment": "comment1"
  },
  "createScript": "create1",
  "dropScript": "drop1",
  "insertScript": "insert1"
}

###


GET http://localhost:8080/sqlscript/getbyid/2

###


GET http://localhost:8080/sqlscript/get_all
Accept: application/json

###
