POST http://localhost:8080/student/add_student
Content-Type: application/json

{
  "firstName": "Sabrina",
  "lastName": "Haus",
  "password": "ADMIN",
  "classname": "test"
}

###

GET http://localhost:8080/student/getbyid/1


###

GET http://localhost:8080/student/get_all
Accept: application/json

###
